#!/usr/bin/env bash
# doctor.sh — drift report. --fix regenerates. Read-only by default.
set -euo pipefail

MOD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/platform.sh
source "$MOD_DIR/lib/platform.sh"

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
CLAUDE_DIR="${CLAUDE_DIR:-$DOTFILES_DIR/.claude}"
PLATFORM="${PLATFORM:-$(detect_platform)}"
FIX=0

for arg in "$@"; do
    [ "$arg" = "--fix" ] && FIX=1
done

issues=0
say() { printf '%s\n' "$@"; }
warn() { printf '⚠ %s\n' "$@"; issues=$((issues + 1)); }
ok()   { printf '✓ %s\n' "$@"; }

say "━━ claude-settings doctor (platform=$PLATFORM) ━━"

# 1. Required files present + valid JSON
for f in "$CLAUDE_DIR/settings.base.json" \
         "$CLAUDE_DIR/settings.${PLATFORM}.json" \
         "$CLAUDE_DIR/_merge-config.json"; do
    if [ ! -f "$f" ]; then
        warn "missing required file: $f"
    elif ! jq empty "$f" >/dev/null 2>&1; then
        warn "invalid JSON: $f"
    else
        ok "valid: $(basename "$f")"
    fi
done

# 2. Override (optional)
if [ -f "$CLAUDE_DIR/settings.override.json" ]; then
    if ! jq empty "$CLAUDE_DIR/settings.override.json" >/dev/null 2>&1; then
        warn "invalid JSON: settings.override.json"
    else
        ok "valid: settings.override.json (present)"
    fi
else
    ok "settings.override.json (absent — treated as {})"
fi

# 3. Attestation vs current inputs
ATTEST="$CLAUDE_DIR/.settings-attestation"
if [ ! -f "$ATTEST" ]; then
    warn "no attestation — settings.local.json may not have been generated by merge.sh"
else
    expected=$(cat "$ATTEST")
    actual=$({
        sha256sum "$CLAUDE_DIR/settings.base.json" "$CLAUDE_DIR/settings.${PLATFORM}.json" "$CLAUDE_DIR/_merge-config.json" 2>/dev/null \
          || shasum -a 256 "$CLAUDE_DIR/settings.base.json" "$CLAUDE_DIR/settings.${PLATFORM}.json" "$CLAUDE_DIR/_merge-config.json" 2>/dev/null
        if [ -f "$CLAUDE_DIR/settings.override.json" ]; then
            sha256sum "$CLAUDE_DIR/settings.override.json" 2>/dev/null \
              || shasum -a 256 "$CLAUDE_DIR/settings.override.json" 2>/dev/null
        fi
    } | { sha256sum 2>/dev/null || shasum -a 256; } | awk '{print $1}')
    if [ "$expected" = "$actual" ]; then
        ok "attestation matches — settings.local.json is up-to-date"
    else
        warn "attestation mismatch — inputs changed since last merge"
        say "  expected=$expected"
        say "  actual=  $actual"
    fi
fi

# 4. Drift detection: compute what merge would produce; diff against on-disk
if [ -f "$CLAUDE_DIR/settings.local.json" ]; then
    CURRENT=$(mktemp)
    cp "$CLAUDE_DIR/settings.local.json" "$CURRENT"
    "$MOD_DIR/merge.sh" >/dev/null 2>&1 || true
    if ! diff -q <(jq -S . "$CURRENT") <(jq -S . "$CLAUDE_DIR/settings.local.json") >/dev/null 2>&1; then
        warn "settings.local.json drift detected:"
        diff <(jq -S . "$CURRENT") <(jq -S . "$CLAUDE_DIR/settings.local.json") 2>&1 | head -40 | sed 's/^/  /' || true
        if [ "$FIX" -ne 1 ]; then
            cp "$CURRENT" "$CLAUDE_DIR/settings.local.json"
            say "  (use --fix to apply)"
        else
            ok "applied: regenerated settings.local.json"
        fi
    else
        ok "no drift in settings.local.json"
    fi
    rm -f "$CURRENT"
fi

say ""
if [ "$issues" -eq 0 ]; then
    ok "doctor clean."
    exit 0
else
    warn "$issues issue(s). Run with --fix to reconcile."
    exit 1
fi
