#!/usr/bin/env bash
# doctor.sh — drift report. --fix regenerates. Read-only by default.
set -euo pipefail

MOD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/platform.sh
source "$MOD_DIR/lib/platform.sh"

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
CLAUDE_DIR="${CLAUDE_DIR:-$DOTFILES_DIR/.claude}"
PLATFORM="${PLATFORM:-$(detect_platform)}"
FIX=0

for arg in "$@"; do
    [ "$arg" = "--fix" ] && FIX=1
done

issues=0
say() { printf '%s\n' "$@"; }
warn() { printf '⚠ %s\n' "$@"; issues=$((issues + 1)); }
ok()   { printf '✓ %s\n' "$@"; }

say "━━ claude-settings doctor (platform=$PLATFORM) ━━"

# 1. Required files present + valid JSON
for f in "$CLAUDE_DIR/settings.base.json" \
         "$CLAUDE_DIR/settings.${PLATFORM}.json" \
         "$CLAUDE_DIR/_merge-config.json"; do
    if [ ! -f "$f" ]; then
        warn "missing required file: $f"
    elif ! jq empty "$f" >/dev/null 2>&1; then
        warn "invalid JSON: $f"
    else
        ok "valid: $(basename "$f")"
    fi
done

# 2. Override (optional)
if [ -f "$CLAUDE_DIR/settings.override.json" ]; then
    if ! jq empty "$CLAUDE_DIR/settings.override.json" >/dev/null 2>&1; then
        warn "invalid JSON: settings.override.json"
    else
        ok "valid: settings.override.json (present)"
    fi
else
    ok "settings.override.json (absent — treated as {})"
fi

# 3. Attestation vs current inputs
ATTEST="$CLAUDE_DIR/.settings-attestation"
if [ ! -f "$ATTEST" ]; then
    warn "no attestation — settings.local.json may not have been generated by merge.sh"
else
    expected=$(cat "$ATTEST")
    actual=$({
        sha256sum "$CLAUDE_DIR/settings.base.json" "$CLAUDE_DIR/settings.${PLATFORM}.json" "$CLAUDE_DIR/_merge-config.json" 2>/dev/null \
          || shasum -a 256 "$CLAUDE_DIR/settings.base.json" "$CLAUDE_DIR/settings.${PLATFORM}.json" "$CLAUDE_DIR/_merge-config.json" 2>/dev/null
        if [ -f "$CLAUDE_DIR/settings.override.json" ]; then
            sha256sum "$CLAUDE_DIR/settings.override.json" 2>/dev/null \
              || shasum -a 256 "$CLAUDE_DIR/settings.override.json" 2>/dev/null
        fi
    } | { sha256sum 2>/dev/null || shasum -a 256; } | awk '{print $1}')
    if [ "$expected" = "$actual" ]; then
        ok "attestation matches — settings.local.json is up-to-date"
    else
        warn "attestation mismatch — inputs changed since last merge"
        say "  expected=$expected"
        say "  actual=  $actual"
        [ "$FIX" -eq 1 ] && issues=$((issues - 1))
    fi
fi

# 4. Drift detection: compute what merge would produce; diff against on-disk
if [ -f "$CLAUDE_DIR/settings.local.json" ]; then
    CURRENT=$(mktemp)
    cp "$CLAUDE_DIR/settings.local.json" "$CURRENT"
    "$MOD_DIR/merge.sh" >/dev/null 2>&1 || true
    if ! diff -q <(jq -S . "$CURRENT") <(jq -S . "$CLAUDE_DIR/settings.local.json") >/dev/null 2>&1; then
        warn "settings.local.json drift detected:"
        diff <(jq -S . "$CURRENT") <(jq -S . "$CLAUDE_DIR/settings.local.json") 2>&1 | head -40 | sed 's/^/  /' || true
        if [ "$FIX" -ne 1 ]; then
            cp "$CURRENT" "$CLAUDE_DIR/settings.local.json"
            say "  (use --fix to apply)"
        else
            ok "applied: regenerated settings.local.json"
            issues=$((issues - 1))
        fi
    else
        ok "no drift in settings.local.json"
    fi
    rm -f "$CURRENT"
fi

# 5. Cursor alignment drift (agent-core -> ~/.cursor)
SYNC_SCRIPT="$DOTFILES_DIR/scripts/agent-core-sync.sh"
AGENT_CORE="$CLAUDE_DIR/agent-core.json"
CURSOR_DIR="${CURSOR_DIR:-$HOME/.cursor}"
CURSOR_CLI="$CURSOR_DIR/cli-config.json"
CURSOR_MCP="$CURSOR_DIR/mcp.json"

if [ -f "$AGENT_CORE" ] && [ -x "$SYNC_SCRIPT" ]; then
    if [ ! -d "$CURSOR_DIR" ]; then
        ok "Cursor dir missing — skipping cursor drift check"
    else
        before_cli="$(mktemp)"
        before_mcp="$(mktemp)"
        had_cli=0
        had_mcp=0
        if [ -f "$CURSOR_CLI" ]; then cp "$CURSOR_CLI" "$before_cli"; had_cli=1; fi
        if [ -f "$CURSOR_MCP" ]; then cp "$CURSOR_MCP" "$before_mcp"; had_mcp=1; fi

        if "$SYNC_SCRIPT" --quiet; then
            cli_changed=0
            mcp_changed=0

            if [ "$had_cli" -eq 1 ]; then
                cmp -s "$before_cli" "$CURSOR_CLI" || cli_changed=1
            elif [ -f "$CURSOR_CLI" ]; then
                cli_changed=1
            fi

            if [ "$had_mcp" -eq 1 ]; then
                cmp -s "$before_mcp" "$CURSOR_MCP" || mcp_changed=1
            elif [ -f "$CURSOR_MCP" ]; then
                mcp_changed=1
            fi

            if [ "$cli_changed" -eq 1 ] || [ "$mcp_changed" -eq 1 ]; then
                warn "cursor drift detected (agent-core sync needed)"
                if [ "$FIX" -ne 1 ]; then
                    if [ "$had_cli" -eq 1 ]; then cp "$before_cli" "$CURSOR_CLI"; else rm -f "$CURSOR_CLI"; fi
                    if [ "$had_mcp" -eq 1 ]; then cp "$before_mcp" "$CURSOR_MCP"; else rm -f "$CURSOR_MCP"; fi
                    say "  (use --fix to apply cursor sync)"
                else
                    ok "applied: synced Cursor from agent-core"
                    issues=$((issues - 1))
                fi
            else
                ok "no cursor drift (agent-core aligned)"
            fi
        else
            warn "agent-core-sync failed during cursor drift check"
            if [ "$had_cli" -eq 1 ]; then cp "$before_cli" "$CURSOR_CLI"; else rm -f "$CURSOR_CLI"; fi
            if [ "$had_mcp" -eq 1 ]; then cp "$before_mcp" "$CURSOR_MCP"; else rm -f "$CURSOR_MCP"; fi
        fi

        rm -f "$before_cli" "$before_mcp"
    fi
fi

say ""
if [ "$issues" -eq 0 ]; then
    ok "doctor clean."
    exit 0
else
    if [ "$FIX" -eq 1 ]; then
        warn "$issues issue(s) require manual attention."
    else
        warn "$issues issue(s). Run with --fix to reconcile."
    fi
    exit 1
fi
