#!/usr/bin/env bash
# Regenerate ~/Projects/README.md with current structure overview.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

OUT="$PROJECTS_ROOT/README.md"

{
    printf '# Projects\n\n'
    printf '_Auto-generated by scripts/projects/gen-readme.sh — do not edit by hand._\n\n'
    printf '## Structure\n\n'
    printf '| Top dir | Purpose | Repos |\n|---|---|---:|\n'
    for d in clients internal personal sandbox _archive _assets; do
        if [[ -d "$PROJECTS_ROOT/$d" ]]; then
            count=$(find "$PROJECTS_ROOT/$d" -maxdepth 4 -type d -name '.git' 2>/dev/null | wc -l | tr -d ' ')
            case "$d" in
                clients) purpose="Client work, grouped by client" ;;
                internal) purpose="AKQA internal tools" ;;
                personal) purpose="Personal projects" ;;
                sandbox) purpose="Templates, experiments, tests" ;;
                _archive) purpose="Old/duplicate repos (kept for reference)" ;;
                _assets) purpose="Loose files (not code)" ;;
            esac
            printf '| `%s/` | %s | %d |\n' "$d" "$purpose" "$count"
        fi
    done

    printf '\n## Clients\n\n'
    if [[ -d "$PROJECTS_ROOT/clients" ]]; then
        for c in "$PROJECTS_ROOT/clients"/*/; do
            [[ -d "$c" ]] || continue
            cname=$(basename "$c")
            printf '### %s\n\n' "$cname"
            for r in "$c"*/; do
                [[ -d "$r" ]] || continue
                rname=$(basename "$r")
                printf -- '- `%s`\n' "$rname"
            done
            printf '\n'
        done
    fi

    printf '\n## Sessionizer\n\n'
    printf 'A flat symlink farm at `~/.zellij-projects/` exposes every repo to zellij-sessionizer.\n'
    printf 'Run `scripts/projects/sync-symlinks.sh` to regenerate it after cloning new repos.\n'
} > "$OUT"

ok "Wrote $OUT"
