#!/usr/bin/env bash
# Install Zed config from dotfiles.
# - settings.json: generated by merging settings.base.json + settings.local.json
# - keymap.json, rules: symlinked directly
# Cross-platform: Windows (via WSL), macOS, Linux.

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log_info()    { echo -e "${BLUE}[zed]${NC} $1"; }
log_success() { echo -e "${GREEN}[zed]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[zed]${NC} $1"; }
log_error()   { echo -e "${RED}[zed]${NC} $1"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ZED_SOURCE="$SCRIPT_DIR/.config/zed"

# Resolve target Zed config directory
if [[ "$OSTYPE" == "darwin"* ]]; then
    ZED_TARGET="$HOME/Library/Application Support/Zed"
elif grep -qi microsoft /proc/version 2>/dev/null; then
    WIN_USER="${USERNAME:-christian}"
    ZED_TARGET="/mnt/c/Users/$WIN_USER/AppData/Roaming/Zed"
else
    ZED_TARGET="$HOME/.config/zed"
fi

log_info "Source : $ZED_SOURCE"
log_info "Target : $ZED_TARGET"

if [[ ! -d "$ZED_TARGET" ]]; then
    log_warning "Zed config dir not found: $ZED_TARGET — is Zed installed?"
    exit 1
fi

# Symlink a file with backup of any existing non-symlink
link_file() {
    local src="$1" dst="$2" label="$3"
    [[ ! -e "$src" ]] && { log_warning "Source missing, skipping: $src"; return 0; }
    [[ -L "$dst" ]] && rm "$dst"
    [[ -e "$dst" ]] && { local bak="${dst}.backup.$(date +%Y%m%d_%H%M%S)"; log_warning "Backing up: $dst → $bak"; mv "$dst" "$bak"; }
    ln -sf "$src" "$dst"
    log_success "Linked $label"
}

# settings.json: merge base + local (not a symlink — contains machine-specific data)
log_info "Merging settings …"
bash "$SCRIPT_DIR/scripts/zed/merge-zed-settings.sh"

# keymap and rules: plain symlinks (no machine-specific content)
link_file "$ZED_SOURCE/keymap.json" "$ZED_TARGET/keymap.json" "keymap.json"
link_file "$ZED_SOURCE/rules"       "$ZED_TARGET/rules"       "rules"

log_success "Zed config installed."
log_info "To add machine-specific settings: create $ZED_SOURCE/settings.local.json"
log_info "  (see settings.local.example.json for reference)"
log_info "Then re-run: bash scripts/zed/merge-zed-settings.sh"
