#!/bin/bash
export JIRA_URL="${ATLASSIAN_FISKARS_JIRA_URL}"
export JIRA_USERNAME="${ATLASSIAN_USERNAME}"
export JIRA_API_TOKEN="${ATLASSIAN_API_TOKEN}"
export CONFLUENCE_URL="${ATLASSIAN_FISKARS_CONFLUENCE_URL}"
export CONFLUENCE_USERNAME="${ATLASSIAN_USERNAME}"
export CONFLUENCE_API_TOKEN="${ATLASSIAN_API_TOKEN}"
exec mcp-atlassian
