#!/usr/bin/env bash
MODULE_NAME="starship"
MODULE_DESC="Starship prompt"
MODULE_CATEGORY="shell"
MODULE_PLATFORMS="all"
MODULE_PROFILES="all"
MODULE_CORE=false
MODULE_DEPENDS=""
MODULE_REQUIRES=""
MODULE_DEFAULT_ENABLED=true
