#!/usr/bin/env bash
# brain-migrate.sh — convert single-file brain to modular dir layout
# Usage: brain-migrate.sh <slug>
set -euo pipefail

SLUG="${1:-}"
[[ -z "$SLUG" ]] && { echo "Usage: brain-migrate.sh <slug>" >&2; exit 1; }

# Platform detection
if grep -qi microsoft /proc/version 2>/dev/null || [[ -n "${WSL_DISTRO_NAME:-}" ]]; then
  VAULT_BRAINS="/mnt/c/Users/christian/Obsidian/Brain/Brains"
else
  VAULT_BRAINS="$HOME/Vaults/Brain/Brains"
fi

SRC="${VAULT_BRAINS}/${SLUG}.md"
DST="${VAULT_BRAINS}/${SLUG}"

[[ -f "$SRC" ]] || { echo "Error: not found: $SRC" >&2; exit 1; }
[[ -d "$DST" ]] && { echo "Error: already exists: $DST" >&2; exit 1; }

mkdir -p "$DST/history" "$DST/archive"

TODAY="$(date '+%Y-%m-%d')"
NOW_TS="$(date '+%Y-%m-%d-%H%M')"

python3 - "$SRC" "$DST" "$TODAY" "$NOW_TS" "$SLUG" <<'PYEOF'
import sys, re, os
from pathlib import Path

src_path, dst_dir, today, now_ts, slug = sys.argv[1:6]

raw = Path(src_path).read_text()

def write_atomic(path, text):
    tmp = path + '.tmp'
    Path(tmp).write_text(text)
    os.rename(tmp, path)

# Extract frontmatter block (between first and second ---)
fm_match = re.match(r'^---\n(.*?)\n---\n?', raw, re.DOTALL)
if fm_match:
    frontmatter = fm_match.group(0)
    frontmatter = re.sub(r'^(updated:\s*).*$', rf'\g<1>{today}', frontmatter, flags=re.MULTILINE)
    body = raw[len(fm_match.group(0)):].lstrip()
else:
    frontmatter = ''
    body = raw

# Split body on "## " at line start; collect sections
parts = re.split(r'^(## .+)$', body, flags=re.MULTILINE)
# parts = [pre, header1, content1, header2, content2, ...]
sections = {}
dated_sections = []
i = 1
while i < len(parts) - 1:
    header_line = parts[i].strip()
    content = parts[i + 1]
    header_text = re.sub(r'^## ', '', header_line).strip()
    if re.match(r'^\d{4}-\d{2}-\d{2}', header_text):
        dated_sections.append((header_line, content))
    else:
        sections[header_text] = content.strip()
    i += 2

def get(name):
    return sections.get(name, '')

# current.md
chunks = [frontmatter, f'# Brain: {slug}\n']
cs = get('Current State')
if cs:
    chunks.append(f'\n## Current State\n\n{cs}')
conv = get('Conventions')
if conv:
    chunks.append(f'\n\n## Conventions\n\n{conv}')
xref = get('Cross-references')
if xref:
    chunks.append(f'\n\n## Cross-references\n\n{xref}')
write_atomic(f'{dst_dir}/current.md', '\n'.join(chunks) + '\n')

# gotchas.md
write_atomic(f'{dst_dir}/gotchas.md', f'# Gotchas: {slug}\n\n{get("Gotchas")}\n')

# next.md — numbered list → bullet items
next_raw = get('Open Decisions / Next Steps')
next_converted = re.sub(r'^\d+\. ', '- ', next_raw, flags=re.MULTILINE)
write_atomic(f'{dst_dir}/next.md', f'# Next: {slug}\n\n{next_converted}\n')

# history: dated sections from source
if dated_sections:
    hist = '\n'.join(f'{h}\n{c}' for h, c in dated_sections).strip()
    write_atomic(f'{dst_dir}/history/{now_ts}.md', hist + '\n')

# INDEX.md (initial — regenerated by cheap-optimise each session)
def first_content_line(text):
    in_fm = False
    for i, l in enumerate(text.splitlines()):
        if i == 0 and l.strip() == '---':
            in_fm = True
            continue
        if in_fm and l.strip() == '---':
            in_fm = False
            continue
        if in_fm:
            continue
        if l and not l.startswith('#'):
            return l
    return '—'

lines = [f'# Brain index: {slug}']
for fname in ['current.md', 'gotchas.md', 'next.md']:
    fpath = Path(dst_dir) / fname
    if fpath.exists():
        text = fpath.read_text()
        lc = len(text.splitlines())
        first = first_content_line(text)
        lines.append(f'- {fname} ({lc}L) — {first[:60]}')
hist_files = sorted((Path(dst_dir) / 'history').glob('*.md'))
last_hist = hist_files[-1].stem if hist_files else 'none'
lines.append(f'- history/ — {len(hist_files)} session(s), last {last_hist}')
write_atomic(f'{dst_dir}/INDEX.md', '\n'.join(lines) + '\n')
PYEOF

# Backup original, keep modular dir
mv "$SRC" "${SRC}.legacy"
echo "Migrated: ${SRC} → ${DST}/"
echo "Backup: ${SRC}.legacy"
ls -la "${DST}/"
