#!/usr/bin/env bash
# opencode-web-traefik — generate Traefik file provider config for opencode web UI
set -euo pipefail

HOSTNAME="${1:-opencode.superbro.ts.net}"
TRAEFIK_DIR="${TRAEFIK_DIR:-$HOME/traefik}"

usage() {
    cat >&2 <<'EOF'
opencode-web-traefik — generate Traefik config for opencode web UI

Usage: opencode-web-traefik [hostname] [traefik-dir]

Arguments:
  hostname     Hostname for the route (default: opencode.superbro.ts.net)
  traefik-dir  Directory for the config file (default: ~/traefik)

Generates an opencode.yml file for Traefik's file provider that:
  - Routes opencode.superbro.ts.net → http://127.0.0.1:4096
  - Applies tinyauth middleware (forwardauth)
  - Handles SSE/streaming headers

Add to your Traefik static config (traefik.yml):
  providers:
    file:
      directory: /home/christian/traefik
      watch: true

Or mount this directory in your Docker Traefik container.
EOF
    exit 0
}

case "${HOSTNAME}" in
    --help|-h|help) usage ;;
esac

mkdir -p "$TRAEFIK_DIR"

cat > "$TRAEFIK_DIR/opencode.yml" <<YAML
# opencode web UI — Traefik file provider config
# Generated by opencode-web-traefik
# Requires: tinyauth middleware defined in your main Traefik config

http:
  routers:
    opencode:
      rule: Host(\`${HOSTNAME}\`)
      entryPoints: ["web"]
      service: opencode
      middlewares: ["tinyauth"]

  services:
    opencode:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:4096"
YAML

echo "Config written to: $TRAEFIK_DIR/opencode.yml"
echo ""
echo "Ensure your Traefik static config includes:"
echo "  providers:"
echo "    file:"
echo "      directory: $TRAEFIK_DIR"
echo "      watch: true"
echo ""
echo "And that tinyauth middleware is defined (e.g. in a middlewares.yml):"
echo "  http:"
echo "    middlewares:"
echo "      tinyauth:"
echo "        forwardAuth:"
echo "          address: \"http://tinyauth:3000/api/auth/traefik\""
echo "          trustForwardHeader: true"
echo "          authResponseHeaders: [\"X-Forwarded-User\"]"
