#!/usr/bin/env bash
# =============================================================================
# GNOME dconf Settings Backup Script
# =============================================================================
# This script backs up important GNOME settings to dconf-settings.ini
# Run this before making changes to preserve your current configuration
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_FILE="$SCRIPT_DIR/dconf-settings.ini"

echo "==================================="
echo "GNOME dconf Backup Script"
echo "==================================="
echo ""

# Check if dconf is available
if ! command -v dconf &> /dev/null; then
    echo "❌ Error: dconf is not installed"
    echo "   Install it with: sudo pacman -S dconf (Arch) or sudo apt install dconf-cli (Debian/Ubuntu)"
    exit 1
fi

# Check if running GNOME
if [ "$XDG_CURRENT_DESKTOP" != "GNOME" ]; then
    echo "⚠️  Warning: Not running GNOME desktop (detected: $XDG_CURRENT_DESKTOP)"
    read -p "Continue anyway? (y/n): " continue_backup
    if [ "$continue_backup" != "y" ]; then
        echo "Backup cancelled"
        exit 0
    fi
fi

echo "📦 Backing up GNOME settings to: $BACKUP_FILE"
echo ""

# Create backup file with header
cat > "$BACKUP_FILE" << 'EOF'
# =============================================================================
# GNOME dconf Settings Backup
# =============================================================================
# Generated by dconf-backup.sh
# Restore with: ./dconf-restore.sh
# =============================================================================

EOF

# Backup categories
declare -A CATEGORIES=(
    ["Desktop Interface"]="org/gnome/desktop/interface"
    ["Window Manager"]="org/gnome/desktop/wm"
    ["Shell"]="org/gnome/shell"
    ["Keybindings"]="org/gnome/settings-daemon/plugins/media-keys org/gnome/desktop/wm/keybindings"
    ["Terminal"]="org/gnome/terminal"
    ["Mutter (Window Manager)"]="org/gnome/mutter"
    ["Session"]="org/gnome/desktop/session"
    ["Privacy"]="org/gnome/desktop/privacy"
    ["Notifications"]="org/gnome/desktop/notifications"
)

# Backup each category
for category in "${!CATEGORIES[@]}"; do
    echo "📋 Backing up: $category"
    
    echo "" >> "$BACKUP_FILE"
    echo "# -----------------------------------------------------------------------------" >> "$BACKUP_FILE"
    echo "# $category" >> "$BACKUP_FILE"
    echo "# -----------------------------------------------------------------------------" >> "$BACKUP_FILE"
    
    for path in ${CATEGORIES[$category]}; do
        if dconf list "/$path/" &> /dev/null; then
            echo "" >> "$BACKUP_FILE"
            echo "# $path" >> "$BACKUP_FILE"
            dconf dump "/$path/" >> "$BACKUP_FILE" 2>/dev/null || echo "# (no settings found)" >> "$BACKUP_FILE"
        fi
    done
done

# Backup custom keybindings
echo ""
echo "🔑 Backing up custom keybindings"
echo "" >> "$BACKUP_FILE"
echo "# -----------------------------------------------------------------------------" >> "$BACKUP_FILE"
echo "# Custom Keybindings" >> "$BACKUP_FILE"
echo "# -----------------------------------------------------------------------------" >> "$BACKUP_FILE"
dconf dump "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/" >> "$BACKUP_FILE" 2>/dev/null || echo "# (no custom keybindings)" >> "$BACKUP_FILE"

# Backup GNOME Shell extensions list
echo ""
echo "🧩 Backing up enabled extensions list"
EXTENSIONS_FILE="$SCRIPT_DIR/extensions-enabled.txt"
gsettings get org.gnome.shell enabled-extensions | tr -d "[']" | tr ',' '\n' | sed 's/^ *//' > "$EXTENSIONS_FILE" 2>/dev/null || echo "# No extensions enabled" > "$EXTENSIONS_FILE"

echo ""
echo "✅ Backup completed successfully!"
echo ""
echo "📁 Files created:"
echo "   - $BACKUP_FILE"
echo "   - $EXTENSIONS_FILE"
echo ""
echo "💡 To restore these settings, run: ./dconf-restore.sh"
