#!/usr/bin/env bash
# memory-curator.sh — weekly cron job
# Scans all brain dirs, writes a curator report to the vault.
# Does NOT apply changes — report reviewed manually or via memory-curator agent.
#
# Install (macOS launchd):
#   cp ~/dotfiles/scripts/vault/com.christian.memory-curator.plist ~/Library/LaunchAgents/
#   launchctl load ~/Library/LaunchAgents/com.christian.memory-curator.plist
#
# Manual run:
#   bash ~/dotfiles/scripts/vault/memory-curator.sh
set -uo pipefail

# Platform detection
if grep -qi microsoft /proc/version 2>/dev/null || [[ -n "${WSL_DISTRO_NAME:-}" ]]; then
    VAULT="/mnt/c/Users/christian/Obsidian/Brain"
elif [[ "$(uname)" == "Darwin" ]]; then
    VAULT="$HOME/Vaults/Me"
else
    VAULT="$HOME/Vaults/Me"
fi

BRAINS_DIR="$VAULT/Brains"
REPORT_FILE="$VAULT/brains/curator-report-$(date '+%Y-%m-%d').md"
NOW="$(date '+%Y-%m-%d %H:%M')"
CUTOFF_DAYS=14

[[ -d "$BRAINS_DIR" ]] || { echo "No Brains dir found at $BRAINS_DIR"; exit 0; }

{
    echo "# Memory Curator Report — $NOW"
    echo ""
    echo "> Generated by \`memory-curator.sh\`. Review and invoke the memory-curator agent to apply changes."
    echo ""

    for brain_dir in "$BRAINS_DIR"/*/; do
        [[ -d "$brain_dir" ]] || continue
        slug="$(basename "$brain_dir")"
        next_file="$brain_dir/next.md"
        current_file="$brain_dir/current.md"
        gotchas_file="$brain_dir/gotchas.md"

        issues=()

        # next.md — stale done items
        if [[ -f "$next_file" ]]; then
            cutoff_date="$(date -v-${CUTOFF_DAYS}d '+%Y-%m-%d' 2>/dev/null || date -d "$CUTOFF_DAYS days ago" '+%Y-%m-%d' 2>/dev/null || echo '2000-01-01')"
            stale_count=0
            while IFS= read -r line; do
                if [[ "$line" =~ \[done:\ ([0-9]{4}-[0-9]{2}-[0-9]{2})\] ]]; then
                    done_date="${BASH_REMATCH[1]}"
                    [[ "$done_date" < "$cutoff_date" ]] && ((stale_count++)) || true
                fi
            done < "$next_file"
            [[ $stale_count -gt 0 ]] && issues+=("next.md: $stale_count done items older than ${CUTOFF_DAYS}d — safe to remove")

            total_items=$(grep -c '^\s*[-*]' "$next_file" 2>/dev/null || echo 0)
            [[ "$total_items" -gt 15 ]] && issues+=("next.md: $total_items items — consider archiving oldest")
        fi

        # current.md — over-grown
        if [[ -f "$current_file" ]]; then
            bullet_count=$(grep -c '^\s*[-*]' "$current_file" 2>/dev/null || echo 0)
            [[ "$bullet_count" -gt 6 ]] && issues+=("current.md: $bullet_count bullets — trim to top 3-4 most recent")
        fi

        # gotchas.md — size check
        if [[ -f "$gotchas_file" ]]; then
            gotcha_count=$(grep -c '^\s*[-*#]' "$gotchas_file" 2>/dev/null || echo 0)
            [[ "$gotcha_count" -gt 20 ]] && issues+=("gotchas.md: $gotcha_count entries — review for resolved items")
        fi

        if [[ ${#issues[@]} -gt 0 ]]; then
            echo "## $slug"
            echo ""
            for issue in "${issues[@]}"; do
                echo "- $issue"
            done
            echo ""
        fi
    done

    echo "---"
    echo "_To apply: invoke the \`memory-curator\` agent in the relevant project._"
} > "$REPORT_FILE"

echo "Curator report written: $REPORT_FILE"
